M48
; DRILL file {KiCad 9.0.3} date 2025-07-23T14:44:03+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-23T14:44:03+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.150
%
G90
G05
T1
X101.4Y-84.2
X104.2Y-84.1
T2
X118.22Y-73.1
X120.76Y-70.56
X123.3Y-73.1
T3
X84.5Y-94.9
X86.4Y-68.6
X130.5Y-68.3
X130.5Y-96.5
M30
